/**
 * Character roster - twelve racers. Stats are 0..1 and trade off by weight
 * class: light = agile/quick off the line, heavy = fast top end but ponderous.
 *
 * Every racer carries its own body scale, rear wing and helmet crest so they
 * stay apart at a distance, not just by paint. Eight of the twelve make the
 * grid each race (KART_COUNT), so the field changes between runs.
 */
import type { CharacterDef } from '../core/types';

export const CHARACTERS: CharacterDef[] = [
  // --- light ---------------------------------------------------------------
  {
    id: 'bzizla',
    name: 'Bzizla',
    color: 0xff3ea5,
    accent: 0xb6ff2e,
    driverColor: 0xfff0fa,
    weightClass: 'light',
    stats: { speed: 0.14, acceleration: 0.95, handling: 0.94, weight: 0.08, miniTurbo: 0.9 },
    tagline: 'Tiny, loud, and already two corners ahead.',
    fin: 'twin',
    crest: 'antenna',
    number: 1,
    kartScale: 0.9,
  },
  {
    id: 'zniqui',
    name: 'Zniqui',
    color: 0x18d8f0,
    accent: 0xff7a1a,
    driverColor: 0x102030,
    weightClass: 'light',
    stats: { speed: 0.2, acceleration: 0.92, handling: 0.9, weight: 0.14, miniTurbo: 0.95 },
    tagline: 'Knows an alley that is not on the map.',
    fin: 'blade',
    crest: 'mohawk',
    number: 2,
    kartScale: 0.92,
  },
  {
    id: 'aicha',
    name: 'Aicha',
    color: 0x8b5cf6,
    accent: 0xffd23f,
    driverColor: 0xf7e6ff,
    weightClass: 'light',
    stats: { speed: 0.24, acceleration: 0.88, handling: 0.86, weight: 0.18, miniTurbo: 0.88 },
    tagline: 'Polite on the podium, ruthless in the hairpin.',
    fin: 'halo',
    crest: 'crown',
    number: 3,
    kartScale: 0.94,
  },
  {
    id: 'nugget',
    name: 'Nugget',
    color: 0xffc21f,
    accent: 0x8a4b12,
    driverColor: 0x3a2410,
    weightClass: 'light',
    stats: { speed: 0.18, acceleration: 0.9, handling: 0.92, weight: 0.12, miniTurbo: 0.86 },
    tagline: 'Bite-sized. Deep-fried. Weirdly fast.',
    fin: 'ducktail',
    crest: 'cap',
    number: 4,
    kartScale: 0.9,
  },
  // --- medium --------------------------------------------------------------
  {
    id: 'diae',
    name: 'Diae',
    color: 0xe32222,
    accent: 0xffffff,
    driverColor: 0xfff6f2,
    weightClass: 'medium',
    stats: { speed: 0.56, acceleration: 0.56, handling: 0.58, weight: 0.5, miniTurbo: 0.58 },
    tagline: 'The all-rounder. Every lap is a highlight reel.',
    fin: 'wing',
    crest: 'none',
    number: 5,
    kartScale: 1,
  },
  {
    id: 'bghrir',
    name: 'Bghrir',
    color: 0xf6e0a8,
    accent: 0xd98026,
    driverColor: 0x6b4413,
    weightClass: 'medium',
    stats: { speed: 0.5, acceleration: 0.62, handling: 0.6, weight: 0.44, miniTurbo: 0.52 },
    tagline: 'A thousand holes, none of them in his defence.',
    fin: 'none',
    crest: 'toque',
    number: 6,
    kartScale: 1,
  },
  {
    id: 'gary',
    name: 'Gary Gearbox',
    color: 0x1e6bff,
    accent: 0xc9d4e4,
    driverColor: 0x0e1c33,
    weightClass: 'medium',
    stats: { speed: 0.62, acceleration: 0.46, handling: 0.52, weight: 0.55, miniTurbo: 0.66 },
    tagline: 'Talks about torque. Nobody asked.',
    fin: 'blade',
    crest: 'none',
    number: 7,
    kartScale: 1.02,
  },
  {
    id: 'kaskrout',
    name: 'Kaskrout',
    color: 0xff6a00,
    accent: 0x2fbf5a,
    driverColor: 0x2b1a0c,
    weightClass: 'medium',
    stats: { speed: 0.58, acceleration: 0.5, handling: 0.54, weight: 0.52, miniTurbo: 0.6 },
    tagline: 'Half sandwich, half sideways.',
    fin: 'ducktail',
    crest: 'horns',
    number: 8,
    kartScale: 1.02,
  },
  // --- heavy ---------------------------------------------------------------
  {
    id: 'l7afozli9',
    name: 'L7afozli9',
    color: 0x5b2b8a,
    accent: 0x9dff2e,
    driverColor: 0x1a0d29,
    weightClass: 'heavy',
    stats: { speed: 0.94, acceleration: 0.2, handling: 0.26, weight: 0.94, miniTurbo: 0.32 },
    tagline: 'Memorises the whole rulebook, then parks on it.',
    fin: 'wing',
    crest: 'horns',
    number: 9,
    kartScale: 1.12,
  },
  {
    id: 'l7ezza9',
    name: 'L7ezza9',
    color: 0xd98f16,
    accent: 0x1b1b20,
    driverColor: 0x40260a,
    weightClass: 'heavy',
    stats: { speed: 0.9, acceleration: 0.24, handling: 0.3, weight: 0.9, miniTurbo: 0.36 },
    tagline: 'Gets on your bumper and stays there. Forever.',
    fin: 'twin',
    crest: 'antenna',
    number: 10,
    kartScale: 1.1,
  },
  {
    id: 'bigkevin',
    name: 'Big Kevin',
    color: 0x16305c,
    accent: 0xff8a1e,
    driverColor: 0xffd9b0,
    weightClass: 'heavy',
    stats: { speed: 1, acceleration: 0.15, handling: 0.24, weight: 0.98, miniTurbo: 0.3 },
    tagline: 'Not angry. Just extremely wide.',
    fin: 'wing',
    crest: 'cap',
    number: 11,
    kartScale: 1.16,
  },
  {
    id: 'wanda',
    name: 'Wanda Waffles',
    color: 0xc98a4b,
    accent: 0xff4d8d,
    driverColor: 0x3d2412,
    weightClass: 'heavy',
    stats: { speed: 0.88, acceleration: 0.28, handling: 0.34, weight: 0.86, miniTurbo: 0.4 },
    tagline: 'Runs on syrup. Brakes are a suggestion.',
    fin: 'halo',
    crest: 'toque',
    number: 12,
    kartScale: 1.08,
  },
];

export function getCharacter(id: string): CharacterDef {
  for (let i = 0; i < CHARACTERS.length; i++) {
    if (CHARACTERS[i].id === id) return CHARACTERS[i];
  }
  return CHARACTERS[0];
}
